apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment #metadata for deps
  labels:
    app: mysql

spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
  template:
    metadata: #metadata for pod
      labels:
        app: two-tier-app
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "admin"  # cluster ip
            - name: MYSQL_PASSWORD
              value: "admin"
            - name: MYSQL_USER
              value: "admin"
            - name: MYSQL_DATABASE
              value: "myDb" 
          ports:
            - containerPort: 3306
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysqldata 
      volumes:
        - name: mysqldata
          persistentVolumeClaim:
            claimName: mysql-pvc