apiVersion: v1
kind: Service
metadata:
  name: two-tier-app
spec:
  selector: # label for dep
    app: two-tier-app
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 5000
      nodePort: 3007
 