apiVersion: v1
kind: Pod
metadata:
  name: two-tier-app-pod
spec:
  containers:
    - name: two-tier-app-pod
      image: kroos31/flaskapp:latest
      env:
        - name: MYSQL_HOST
          value: "mysql"  # cluster ip
        - name: MYSQL_PASSWORD
          value: "admin"
        - name: MYSQL_USER
          value: "admin"
        - name: MYSQL_DB
          value: "myDb" 
      ports:
        - containerPort: 5000
      imagePullPolicy: Always
